apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: testgo2-gitops
  description: This is GitOps manifest for testgo2   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: testgo2
    janus-idp.io/tekton: testgo2
    backstage.io/kubernetes-id: testgo2 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:testgo2
