apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: testgo2
  janus-idp.io/tekton: testgo2
  backstage.io/kubernetes-id: testgo2
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: testgo2
resources:
- deployment.yaml
- route.yaml
- service.yaml
