apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: testgo2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testgo2 
  name: testgo2
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: testgo2 
